import cv2
import numpy as np
import matplotlib.pyplot as plt
img = cv2.imread("/media/galdrux/galdrux_storage/sem_5/CV/dataset/satellite_9.jpg")
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
h, w = gray.shape
center = (w // 2, h // 2)
M_rotate = cv2.getRotationMatrix2D(center, 45, 1.0)
rotated = cv2.warpAffine(gray, M_rotate, (w, h))
M_translate = np.float32([[1, 0, 50], [0, 1, 30]])
translated = cv2.warpAffine(gray, M_translate, (w, h))
scaled_half = cv2.resize(gray, None, fx=0.5, fy=0.5, interpolation=cv2.INTER_AREA)
scaled_double = cv2.resize(gray, None, fx=2, fy=2, interpolation=cv2.INTER_LINEAR)
horizontal_flip = cv2.flip(gray, 1)
vertical_flip = cv2.flip(gray, 0)
plt.figure(figsize=(14, 8))
plt.subplot(2, 4, 1)
plt.imshow(gray, cmap="gray")
plt.title("Original Grayscale")
plt.axis("off")
plt.subplot(2, 4, 2)
plt.imshow(rotated, cmap="gray")
plt.title("Rotation 45°")
plt.axis("off")
plt.subplot(2, 4, 3)
plt.imshow(translated, cmap="gray")
plt.title("Translation (50,30)")
plt.axis("off")
plt.subplot(2, 4, 4)
plt.imshow(scaled_half, cmap="gray")
plt.title("Scaling 0.5x")
plt.axis("off")
plt.subplot(2, 4, 5)
plt.imshow(scaled_double, cmap="gray")
plt.title("Scaling 2x")
plt.axis("off")
plt.subplot(2, 4, 6)
plt.imshow(horizontal_flip, cmap="gray")
plt.title("Horizontal Flip")
plt.axis("off")
plt.subplot(2, 4, 7)
plt.imshow(vertical_flip, cmap="gray")
plt.title("Vertical Flip")
plt.axis("off")
plt.tight_layout()
plt.show()