import cv2
import numpy as np
import matplotlib.pyplot as plt
img = cv2.imread("/media/galdrux/galdrux_storage/sem_5/CV/dataset/satellite_9.jpg")
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
Gx = cv2.Sobel(gray, cv2.CV_64F, 1, 0, ksize=3)
Gy = cv2.Sobel(gray, cv2.CV_64F, 0, 1, ksize=3)
magnitude = np.sqrt(Gx ** 2 + Gy ** 2)
Gx_display = cv2.convertScaleAbs(Gx)
Gy_display = cv2.convertScaleAbs(Gy)
magnitude_display = cv2.convertScaleAbs(magnitude)
plt.figure(figsize=(12, 4))
plt.subplot(1, 3, 1)
plt.imshow(Gx_display, cmap="gray")
plt.title("Sobel Gx")
plt.axis("off")
plt.subplot(1, 3, 2)
plt.imshow(Gy_display, cmap="gray")
plt.title("Sobel Gy")
plt.axis("off")
plt.subplot(1, 3, 3)
plt.imshow(magnitude_display, cmap="gray")
plt.title("Gradient Magnitude")
plt.axis("off")
plt.tight_layout()
plt.show()