import cv2
import matplotlib.pyplot as plt
img = cv2.imread("/media/galdrux/galdrux_storage/sem_5/CV/dataset/satellite_9.jpg")
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
laplacian = cv2.Laplacian(gray, cv2.CV_64F)
laplacian = cv2.convertScaleAbs(laplacian)
canny1 = cv2.Canny(gray, 50, 150)
canny2 = cv2.Canny(gray, 100, 200)
plt.figure(figsize=(12, 4))
plt.subplot(1, 3, 1)
plt.imshow(laplacian, cmap="gray")
plt.title("Laplacian")
plt.axis("off")
plt.subplot(1, 3, 2)
plt.imshow(canny1, cmap="gray")
plt.title("Canny (50,150)")
plt.axis("off")
plt.subplot(1, 3, 3)
plt.imshow(canny2, cmap="gray")
plt.title("Canny (100,200)")
plt.axis("off")
plt.tight_layout()
plt.show()